### ISSUE TITLE
Some images run well. However some images could not run,why?

### ISSUE THREAD

**Issue by 102757017** [Spenhouet/automated-deep-photo-style-transfer#3]
Using TensorFlow backend.
Create segmentation.
Compute segmentation started
2019-04-30 14:23:14.863543: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-30 14:23:15.033646: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-04-30 14:23:15.034140: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56271ea411e0 executing computations on platform CUDA. Devices:
2019-04-30 14:23:15.034171: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-04-30 14:23:15.035899: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-04-30 14:23:15.036179: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56271ea41080 executing computations on platform Host. Devices:
2019-04-30 14:23:15.036208: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-30 14:23:15.036524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
totalMemory: 14.73GiB freeMemory: 14.60GiB
2019-04-30 14:23:15.036551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-30 14:23:15.037080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-30 14:23:15.037100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-30 14:23:15.037110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-30 14:23:15.037329: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-04-30 14:23:15.037366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /content/automated-deep-photo-style-transfer/components/PSPNet/network.py:263: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/util/dispatch.py:180: calling expand_dims (from tensorflow.python.ops.array_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Restored model parameters from /content/automated-deep-photo-style-transfer/weights/PSPNet/checkpoint/model.ckpt-0
2019-04-30 14:23:19.381974: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Semantic merge of segments started
Semantic merge of different segments started
Semantic merge of different segments started
Traceback (most recent call last):
  File "/content/automated-deep-photo-style-transfer/style_transfer.py", line 322, in <module>
    args.semantic_thresh)
  File "/content/automated-deep-photo-style-transfer/components/semantic_merge.py", line 93, in merge_segments
    assert style_colors == content_colors
AssertionError

**Comment by paulsans** [comment]
This happens if one of the two segmentation masks contains color values that are not contained in the other segmentation mask. If the segmentation masks are created automatically, this is a bug. In this case, it would be great if you could share the input images you are using, so we can work on a fix. If the segmentation masks are created manually, then you should make sure that the images contain the same colors. Also make sure that you use nearest-neighbor interpolation when resizing segmentation masks, as other interpolation methods would render additional color values.

**Comment by 102757017** [comment]
The segmentation masks are created automatically，Here are the pictures I used。
style.png：https://drive.google.com/file/d/1p33Bu1_T1jSEzqxTigdqro72l-Q2uSh9/view?usp=sharing
content.png：https://drive.google.com/file/d/1BRbtCvYizBUWXnyq2TJ06zDzzBnkdabM/view?usp=sharing

**Comment by paulsans** [comment]
Looks like the order of colors is causing the assertion error. I've created a pull request for this issue:

https://github.com/Spenhouet/automated-deep-photo-style-transfer/pull/4

**Comment by Spenhouet** [comment]
@102757017 Could you please verify if the fix solved your issue?

**Comment by 102757017** [comment]
I retried，it give another mistake，then stoped.
Using TensorFlow backend.
Load segmentation from files.
Style transfer started
[0510 14:54:57 @registry.py:126] conv1_1 input: [1, None, None, 3]
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[0510 14:54:57 @registry.py:134] conv1_1 output: [1, None, None, 64]
[0510 14:54:57 @registry.py:126] conv1_2 input: [1, None, None, 64]
[0510 14:54:57 @registry.py:134] conv1_2 output: [1, None, None, 64]
[0510 14:54:57 @registry.py:126] pool1 input: [1, None, None, 64]
[0510 14:54:57 @registry.py:134] pool1 output: [1, None, None, 64]
[0510 14:54:57 @registry.py:126] conv2_1 input: [1, None, None, 64]
[0510 14:54:57 @registry.py:134] conv2_1 output: [1, None, None, 128]
[0510 14:54:57 @registry.py:126] conv2_2 input: [1, None, None, 128]
[0510 14:54:57 @registry.py:134] conv2_2 output: [1, None, None, 128]
[0510 14:54:57 @registry.py:126] pool2 input: [1, None, None, 128]
[0510 14:54:57 @registry.py:134] pool2 output: [1, None, None, 128]
[0510 14:54:57 @registry.py:126] conv3_1 input: [1, None, None, 128]
[0510 14:54:57 @registry.py:134] conv3_1 output: [1, None, None, 256]
[0510 14:54:57 @registry.py:126] conv3_2 input: [1, None, None, 256]
[0510 14:54:57 @registry.py:134] conv3_2 output: [1, None, None, 256]
[0510 14:54:57 @registry.py:126] conv3_3 input: [1, None, None, 256]
[0510 14:54:57 @registry.py:134] conv3_3 output: [1, None, None, 256]
[0510 14:54:57 @registry.py:126] conv3_4 input: [1, None, None, 256]
[0510 14:54:57 @registry.py:134] conv3_4 output: [1, None, None, 256]
[0510 14:54:57 @registry.py:126] pool3 input: [1, None, None, 256]
[0510 14:54:57 @registry.py:134] pool3 output: [1, None, None, 256]
[0510 14:54:57 @registry.py:126] conv4_1 input: [1, None, None, 256]
[0510 14:54:57 @registry.py:134] conv4_1 output: [1, None, None, 512]
[0510 14:54:57 @registry.py:126] conv4_2 input: [1, None, None, 512]
[0510 14:54:57 @registry.py:134] conv4_2 output: [1, None, None, 512]
[0510 14:54:57 @registry.py:126] conv4_3 input: [1, None, None, 512]
[0510 14:54:57 @registry.py:134] conv4_3 output: [1, None, None, 512]
[0510 14:54:57 @registry.py:126] conv4_4 input: [1, None, None, 512]
[0510 14:54:57 @registry.py:134] conv4_4 output: [1, None, None, 512]
[0510 14:54:57 @registry.py:126] pool4 input: [1, None, None, 512]
[0510 14:54:57 @registry.py:134] pool4 output: [1, None, None, 512]
[0510 14:54:57 @registry.py:126] conv5_1 input: [1, None, None, 512]
[0510 14:54:57 @registry.py:134] conv5_1 output: [1, None, None, 512]
2019-05-10 14:54:57.341249: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-10 14:54:57.616483: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-10 14:54:57.617338: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a3927f6520 executing computations on platform CUDA. Devices:
2019-05-10 14:54:57.617374: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-05-10 14:54:57.639620: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-05-10 14:54:57.639897: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a3927f63c0 executing computations on platform Host. Devices:
2019-05-10 14:54:57.639947: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-10 14:54:57.640292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
totalMemory: 14.73GiB freeMemory: 14.60GiB
2019-05-10 14:54:57.640319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-10 14:54:57.642323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-10 14:54:57.642355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-05-10 14:54:57.642366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-05-10 14:54:57.642594: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-05-10 14:54:57.642640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
[0510 14:55:00 @sessinit.py:205] Variables to restore from dict: conv4_4/W:0, conv5_1/b:0, conv1_1/b:0, conv3_4/W:0, conv2_1/W:0, conv3_2/W:0, conv3_3/b:0, conv3_4/b:0, conv4_3/W:0, conv1_2/W:0, conv2_2/W:0, conv3_1/W:0, conv4_2/W:0, conv2_2/b:0, conv1_1/W:0, conv3_1/b:0, conv3_3/W:0, conv4_3/b:0, conv3_2/b:0, conv4_4/b:0, conv4_2/b:0, conv4_1/b:0, conv5_1/W:0, conv2_1/b:0, conv1_2/b:0, conv4_1/W:0
[0510 14:55:00 @sessinit.py:87] WRN The following variables are in the graph, but not found in the dict: Variable
[0510 14:55:00 @sessinit.py:87] WRN The following variables are in the dict, but not found in the graph: conv5_2/W, conv5_2/b, conv5_3/W, conv5_3/b, conv5_4/W, conv5_4/b, fc6/W, fc6/b, fc7/W, fc7/b, fc8/W, fc8/b
[0510 14:55:00 @sessinit.py:218] Restoring 26 variables from dict ...
Compute matting laplacian started
^C

**Comment by Spenhouet** [comment]
@102757017 What do you mean with "then stoped"? In the stack you posted there is no mistake / error.
The `^C` indicates that you manually stopped it.

Computing the matting laplacian can take some time. Stylizing a single image can take up at least 30 min. depending on your setup.

**Comment by 102757017** [comment]
I used colab to run this project. When running to the middle, colab prompts that the memory is running out. Then the program is interrupted. Is the memory requirement increased after this revision? How much memory do you need to run in general?

**Comment by Spenhouet** [comment]
@102757017 The memory usage depends on the input image size and the number of segments (based on the chosen threshold). It can get very heavy.

If it takes up more memory than your system provides you can try to reduce the content and style image size.
